package ru.slavapmk.journalTracker.ui

object SharedKeys {
    const val SHARED_APP_ID = "RU.SLAVAPMK.JOURNALTRACKER_VGHDFGDZVUHYFIUJHIOVHGYDZUIFHVDVO_SHARED"
    const val SEMESTER_ID = "SEMESTER_ID"
    const val WEEK_SHARED_ID = "WEEK_INDEX"
    const val WEEK_TYPES_KEY = "WEEK_TYPES_KEY"
    const val WEEK_FORMAT_KEY = "WEEK_FORMAT_KEY"
    const val GROUP_NAME_KEY = "GROUP_NAME_KEY"
    const val ATTENDANCE_FORMAT_KEY = "ATTENDANCE_FORMAT_KEY"
    const val PLUS_MINUS_VALUE_KEY = "PLUS_MINUS"
    const val SKIP_HOURS_VALUE_KEY = "SKIP_HOURS"
    const val EVEN_UNEVEN_VALUE_KEY = "EVEN_UNEVEN"
    const val UP_DOWN_VALUE_KEY = "UP_DOWN"
    const val DOWN_UP_VALUE_KEY = "DOWN_UP"
    const val SELECTED_DAY = "SELECTED_DAY"
    const val SELECTED_MONTH = "SELECTED_MONTH"
    const val SELECTED_YEAR = "SELECTED_YEAR"
    const val SELECTED_ITEM = "SELECTED_ITEM"
    const val SELECTED_LESSON = "SELECTED_LESSON"
}